### ISSUE TITLE
No IP blocking configuration page available after enabling module

### ISSUE THREAD

**Issue by jackaponte** [backdrop-contrib/ip_blocking#1]
I've downloaded and installed ip_blocking-1.x-1.0.1 on my Backdrop 1.11.1 site. After confirming that the "Block IP addresses" permission was granted to the appropriate roles and clearing caches, I still can't access the module's admin page. No such page is available via the admin menu at _Administration > Configuration > User accounts > IP address blocking_. The "Configure" Operations link for the module on the Modules page links to `admin/config/people` instead of `admin/config/people/ip-blocking`, and the latter path only leads to the "User accounts" admin page.

**Comment by findlabnet** [comment]
Thank you for reporting, @jackaponte!
Actually, problem is in files directory permissions after unzipping downloaded file (this is old Github issue) - no one except owner cannot read files within. 
You can just change permission of module directory to 755 recursively (to include "config" subdirectory).
Anyway, today later I'll release new version without such problem.

**Comment by jackaponte** [comment]
Ah, many thanks for the response @findlabnet! I'll either try the new release _or_ apply the fix you suggest. Cheers!

**Comment by findlabnet** [comment]
You are welcome, @jackaponte! Feel free to let me know if anything going wrong.

**Comment by jackaponte** [comment]
Hi again @findlabnet! I just downloaded ip_blocking-1.x-1.0.2 using drush, enabled the module but still couldn't reach a config page, either via the UI or by directly visiting `admin/config/people/ip-blocking`. I uninstalled the module, made sure the permissions were set properly as you suggested, enabled the module again and still no luck!

I wish I had time to put into troubleshooting this myself; perhaps some time will free up in the future. :)

**Comment by findlabnet** [comment]
Sorry about your problem, @jackaponte.
Can you explain current file system permissions exactly as you can see?
Correct permissions for directories(folders) is `755` and for files is `644`.
You can try run within your modules directory:
`chmod -R 755 ip_blocking/`
Please check `admin/reports/dblog` - if Backdrop cannot read directory content, you can see some PHP warnings about this problem.
Have you another Backdrop setup, to check this problem with?

**Comment by jackaponte** [comment]
Apologies for trailing off here years ago! Turned out my problem was solved by disabling backup_migrate on the test site I was using before enabling ip_blocking; that stopped a backup_migrate problem of trying to connect to a database with incorrect credentials, and that allowed ip_blocking to install correctly.
