### ISSUE TITLE
Config page doesn't play nicely with large blocked_ips tables

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ip_blocking#11]
I'm upgrading from D7 with a large `blocked_ips` table (46K entries). That makes the admin form at admin/config/people/ip-blocking HUGE. It would be nice to have a pager and filterable content on this table.

Looks like this could be done by make the table an embedded View (which would allow a variety of filtering and also user customization, e.g., changing the size of the pager). It would be necessary to declare the table to Views and add some custom formatters to handle the special casing on `$ip->uid` and `$time`, but it would be well worth it.

**Comment by findlabnet** [comment]
Paging and sorting are useful for any tabular presentation of data.

I didn't think anyone had such a large number of blocked IP addresses.
How do you deal with it in D7?

My typical use case involves very rare manual blocking, basically this table is populated and then automatically released by the Antiscan module.

**Comment by bugfolder** [comment]
We've had the site for about 10 years so it's grown over time, and we have a bunch of custom auto-blocking that detects various spam-account creation attempts or bad-bot visitation (for example, attempting to visit /wp-admin on a Drupal site). The average is about 20 newly blocked IP addresses per day.

**Comment by findlabnet** [comment]
OK, you can try latest [release](https://github.com/backdrop-contrib/ip_blocking/releases/tag/1.x-1.0.9).
The table now has a pager (50 records per page) and sortable columns.
Hope this helps you with your big data.

**Comment by bugfolder** [comment]
Definitely nicer for page loading, thanks!

I hope that the ability to filter on the various column criteria could be added in the future.

**Comment by findlabnet** [comment]
> ability to filter on the various column criteria

Such filters should require heavy AJAXization, which I prefer to avoid in favor of simplicity.
This is still possible, but as a very low priority task.
I think this specific issue can be closed.

**Comment by findlabnet** [comment]
Exposing a table to views can be an interesting thing (haven't done anything like it yet), but the question is how many people need it.

In the latest release, the historically awkward report has been corrected to be more useful, so maybe this will be the next step in the future.

**Comment by bugfolder** [comment]
The current version works for me (thanks!), so I'm no hurry to expose it to Views, but if you're open to it, I might work on that as time permits.

**Comment by findlabnet** [comment]
Closed as resolved.
