### ISSUE TITLE
Warning: Cannot modify header information

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/ip_blocking#16]
I'm seeing a lot of this in the logs:

> Warning: Cannot modify header information - headers already sent by (output started at /code/core/includes/bootstrap.inc:3132) in ip_blocking_boot() (line 113 of /code/modules/contrib/ip_blocking/ip_blocking.module).

**Comment by findlabnet** [comment]
As a workaround, you can disable prefetching for cached pages.

![cache](https://github.com/backdrop-contrib/ip_blocking/assets/11479969/fd12f7f6-70f0-46ff-b14c-bcab669cb8d8)

I don't have a better solution at the moment, but I'm open to suggestions.

**Comment by Egmund** [comment]
Does this issue mean that the blocked user is not blocked - does not get a 403 or 404?

**Comment by findlabnet** [comment]
Hi @Egmund, you are correct: when Backdrop serves a cached page, 'X-Backdrop-Cache: HIT' and 'cache-control' headers were sent with the stale entries before actually generated for the request.
From the documentation: 
> In hook_boot(), only the most basic APIs are available and not all modules have been loaded. This hook by default is not called on pages served by the default page cache, but can be enabled through the $settings['page_cache_invoke_hook'] option in settings.php.

This option can be used, but note documentation typo: not 'page_cache_invoke_hook' but 'page_cache_invoke_hooks' as in `bootstrap.inc` file, lines 3099 and 3116.

However, in my experience, disabling prefetching for cached pages as described above is sufficient to avoid such collisions.

Additionally, you may want to enable logging on the module settings page to see access attempts from blocked IPs.

**Comment by Egmund** [comment]
Thank you for clarifying.
But this issue should be clearly stated in the instructions for this module, since if background fetch is not disabled/unchecked the module does not do its job. Or - - - ?

**Comment by findlabnet** [comment]
It depends on the current cache expiration status - most of the time the module does its job - except when this warning appears. 
Anyway, I'll add this recommendation to the README.md file with the next release that I'm planning in the next few days.
Thank you.

**Comment by findlabnet** [comment]
Resolved in latest [release](https://github.com/backdrop-contrib/ip_blocking/releases/download/1.x-1.0.14/ip_blocking.zip).
