### ISSUE TITLE
Option to import D7 blocked_ips

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/ip_blocking#17]
When installing this module on top of a site upgraded from D7 that has blocked IPs (in table `blocked_ips`), this module renames that table to `blocked_ips_d7`) and creates its own `blocked_ips` table, which has 3 additional columns: `reason`, `uid`, and `time`.

For people upgrading who have a lot of blocked IPs, they would likely like to keep those IPs blocked. So it would be nice if the `blocked_ips_d7` table exists, to offer admins the option to move those IPs into `blocked_ips`, specifying the reason, uid, and time to use for all of them upon import. And then drop the `blocked_ips_d7` table.

**Comment by findlabnet** [comment]
Thanks, seems to be a useful feature. So, for all of them on import: 
reason is "Imported during migration", uid is current user (who perform the migration) id, and time is import time. 
Seems OK for you?

**Comment by bugfolder** [comment]
> So, for all of them on import:
> reason is "Imported during migration", uid is current user (who perform the migration) id, and time is import time.
> Seems OK for you?

That would probably be OK, but for maximum flexibility, maybe consider creating textfields that let the user set those values during the import, but specifying what you suggested as the default values.

And then also, since the table of blocked IPs could be quite large (on my site, there's over 70K blocked IPs), the import should be done as a batch job to prevent timeouts during the import.

**Comment by findlabnet** [comment]
Resolved in latest [release](https://github.com/backdrop-contrib/ip_blocking/releases/download/1.x-1.0.15/ip_blocking.zip).

I have found bug, so here one more release today.

**Comment by findlabnet** [comment]
Just to note how it was tested.

![rec_80K](https://github.com/backdrop-contrib/ip_blocking/assets/11479969/e2849c37-9bc0-40a7-810f-68570c98c5dc)
