### ISSUE TITLE
More useful information on the `admin/config/people/ip-blocking` page

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ip_blocking#2]
Thanks for porting. 

On one of the projects that we'd like to build on Backdrop one day, the website admins need to be able to manually block visitors and this module seems to be almost perfect candidate. 

However, at the same time they need to see WHEN and WHY that or another IP address was blocked. Unfortunately, currently the module has the same basic features which similar core Drupal 7 had to show only the blocked IP addresses and the unblock operation. Would you consider expanding the module's features to make it more versatile and useful?

**Comment by findlabnet** [comment]
> WHEN and WHY 

and WHO did it.
Yes, it seems to be valuable addition. Next week I'll find some time for it.
Thank you for an idea.

**Comment by findlabnet** [comment]
Done. You can try new version [1.0.3](https://github.com/backdrop-contrib/ip_blocking/releases/download/1.x-1.0.3/ip_blocking.zip).

**Comment by alanmels** [comment]
Works like a charm, thanks a lot!
