### ISSUE TITLE
Table blocked_ips already exists - when upgrading from Drupal 7

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/ip_blocking#5]
> DatabaseSchemaObjectExistsException: Table blocked_ips already exists. in DatabaseSchema->createTable() (line 661 of /app/core/includes/database/schema.inc).

Not sure how to avoid this when there's a schema in the install file. Somehow need to check if the table already exists.

**Comment by herbdool** [comment]
The fatal error interrupts the update hooks. And the schema version ends up staying at -1 in the system table so it can't run the updates at all.

**Comment by findlabnet** [comment]
Seems like checking for existing table need to be added to installer.

**Comment by findlabnet** [comment]
Trying resolve it as [core issue](https://github.com/backdrop/backdrop-issues/issues/4771)

**Comment by herbdool** [comment]
Thanks for doing that @findlabnet. You can probably close this issue then. (In retrospect I could have just renamed the table if I wanted to keep the data.)

**Comment by findlabnet** [comment]
Resolved with new [release](https://github.com/backdrop-contrib/ip_blocking/releases/tag/1.x-1.0.6)
If old table exists when this module install, it will be renamed to `blocked_ips_d7`, then on status report page you can see info about it.
@herbdool , thanks for your help.
