### ISSUE TITLE
Database schema conflict ip_blocking and ban_ip

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/ip_blocking#7]
There are currently two contrib modules which adopt the database table "blocked_ips" from Drupal 7 core.

Both modules define the same table in their hook_schema():

- ip_blocking install file: https://github.com/backdrop-contrib/ip_blocking/blob/master/ip_blocking.install
- ban_ip install file: https://github.com/backdrop-contrib/ban_ip/blob/1.x-1.x/ban_ip.install

Although it's very unlikely that people install both, it's technically possible. Furthermore, D7 migrations already ship with that table (ip_blocking takes care of that, ban_ip doesn't).

Ideally, as both modules have stable releases, this conflict should get resolved.

**Comment by findlabnet** [comment]
@indigoxela, shall I add check if module ban_ip installed?

**Comment by indigoxela** [comment]
@findlabnet actually I'm not sure, what's the best way to handle this. Maybe @docwilmot (listed as ban_ip maintainer) has an idea?

**Comment by docwilmot** [comment]
Whichever module has least installs should be shut down since they do the same thing.

**Comment by indigoxela** [comment]
> Whichever module has least installs should be shut down since they do the same thing.

That sounds (maybe too) radical. :wink: I belief (didn't use either module yet) that ip_blocking does a bit more than ban_ip. If usage is the source for decision, then ban_ip would have to go.

To my knowledge there's no "conflicts = othermodule" in info files (which would be nice here), but for sure there are several options.

1. deprecate and drop one of the modules, referring to the other one as alternative
2. one or both modules rename their db table (does B have best practices for db table names?)
3. both modules do a check in hook_requirements and refuse to install, if the other one is already present
4. ... any other?

**Comment by findlabnet** [comment]
Thanks @indigoxela, I think if we do 3 only, then 1 and 2 will become less critical.

**Comment by docwilmot** [comment]
> That sounds (maybe too) radical. 😉 

Yes it is. 😄 
For some reason I did not expect this module to have more than a couple users. A `hook_requirements()` sounds good.

**Comment by findlabnet** [comment]
I've [done](https://github.com/backdrop-contrib/ip_blocking/releases/tag/1.x-1.0.7).

**Comment by findlabnet** [comment]
Should this ticket remain open until the second module is updated?

**Comment by indigoxela** [comment]
I think it's OK to close this one, as ban_ip has [its own issue](https://github.com/backdrop-contrib/ban_ip/issues/3) for that.

**Comment by findlabnet** [comment]
Thanks @indigoxela, closed.

**Comment by herbdool** [comment]
I'd like to suggest an additional change. I see the warning that `blocked_ips` already exists in your requirements check. But I attempted to install via the command line. In my case using `bee`: `bee en ip_blocking`. And it gave the error: "Table blocked_ips already exists."  Going by the wording I think it's coming from core. So seems like it's not able to check for an existing table before installing. (I'm not sure if there's a better way to do it here, or if maybe there's a problem with how bee installs modules).

**Comment by herbdool** [comment]
One more suggestion: if the `blocked_ips` table gets renamed, it might be good to copy over all the ips to the new table since this is useful information to keep.

**Comment by findlabnet** [comment]
Sorry @herbdool, somehow missed your comments.
I think that with the next minor release, the table for this module should be renamed to avoid problems in the future.

**Comment by bugfolder** [comment]
[See this comment in the equivalent issue in the Ban IP issue queue.](https://github.com/backdrop-contrib/ban_ip/issues/3#issuecomment-1809358467)

**Comment by findlabnet** [comment]
The issues raised have been resolved.
