### ISSUE TITLE
Provide one-click action button/link for IP blocking right on the log page

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/ip_blocking#8]
While browsing _Recent log messages_ (admin/reports/dblog), it would be very nice to be able to quickly review an individual entry and send an offending IP address right from the log page as shown on the screenshot:

![Screen Shot 2021-05-05 at 8 05 33 PM](https://user-images.githubusercontent.com/56604405/117232332-2b8df280-adde-11eb-93b3-fc4e0d552abc.png)

Otherwise, you have to copy the IP address, then navigate to `/admin/config/people/ip-blocking` and manually block an IP address.

**Comment by findlabnet** [comment]
Good idea, Alan! 
I'll see what to do (immediately got additional idea), so thank you!

**Comment by findlabnet** [comment]
Done @alanmels ,you can try [version 1.0.8](https://github.com/backdrop-contrib/ip_blocking/releases/tag/1.x-1.0.8)

Packaging for contribs is currently broken, so new release is not published on b.org yet.

**Comment by findlabnet** [comment]
Packaging fixed, new version available at https://backdropcms.org/project/ip_blocking

**Comment by alanmels** [comment]
Thanks a lot, Vladimir!
